name: Sync Badges to Gist

on:
  push:
    paths:
      - 'Badges/**/*.svg'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Collect and upload SVG files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }} # Token
          GIST_ID: ${{ secrets.GIST_ID }} # ID Gist
        run: |
          npm install @octokit/rest
          node sync-to-gist.js
      
      - name: Notify on failure
        if: failure()
        run: echo "Failed to sync badges to Gist"
